version: '3.8'
services:
  backend:
    build: .
    container_name: devtinder_backend
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis
    container_name: devtinder_redis
    ports:
      - "6379:6379"
